apiVersion: apps/v1
kind: Deployment
metadata:
  name: hot-reloader-nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hot-reloader-nginx
  template:
    metadata:
      name: hot-reloader-nginx
      labels:
        app: hot-reloader-nginx
    spec:
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 30
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-main-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-cd-configmap-volume
              mountPath: /etc/nginx/conf.d/cd
            - name: nginx-ci-configmap-volume
              mountPath: /etc/nginx/conf.d/ci
        - name: nginx-reloader
          image: crushed/nginx-reloader:latest
          imagePullPolicy: Always
          env:
            - name: TIME_AFTER_SECONDS
              value: "10"
            - name: WATCH_DIRS
              value: "/etc/nginx,/etc/nginx/conf.d"
      volumes:
        - name: nginx-main-config-volume
          configMap:
            name: nginx-main-configmap
        - name: nginx-cd-configmap-volume
          configMap:
            name: nginx-cd-configmap
        - name: nginx-ci-configmap-volume
          configMap:
            name: nginx-ci-configmap
---

# https://github.com/kubernetes/examples/blob/master/staging/https-nginx/auto-reload-nginx.sh

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-main-configmap
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/**/*.conf;
    }
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cd-configmap
data:
  nginx.conf: |
    server {
        listen       8080;
        listen  [::]:8080;
        server_name  localhost;
        #access_log  /var/log/nginx/host.access.log  main;

        location / {
            default_type application/json;
            return 200 "Hello 8080, World!1";
        }

        #error_page  404              /404.html;
        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ci-configmap
data:
  ci.conf: |
    server {
      listen       8081;
      listen  [::]:8081;
      server_name  localhost;
      #access_log  /var/log/nginx/host.access.log  main;
    
      location / {
          default_type application/json;
          return 200 "Hello 8081, World!1";
      }
    
      #error_page  404              /404.html;
      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }

